meta:
- desc: |
   setup ceph/pacific v16.2.4

tasks:
- install:
    tag: v16.2.4
    exclude_packages:
      - ceph-volume
- cephadm:
    roleless: true
    image: docker.io/ceph/ceph:v16.2.4
    cephadm_branch: v16.2.4
    cephadm_git_url: https://github.com/ceph/ceph
    # needed for v16.2.4 due to --skip-admin-label
    avoid_pacific_features: true
- print: "**** done starting v16.2.4"
- cephadm.shell:
    host.a:
      - ceph orch status
      - ceph orch ps
      - ceph orch ls
      - ceph orch host ls
      - ceph orch device ls

